first_name_field_locator = ('id', 'firstname')
last_name_field_locator = ('id', 'lastname')
email_field_locator = ('id', 'email_address')
password_field_locator = ('id', 'password')
confirm_password_field_locator = ('id', 'password-confirmation')
submit_button_locator = ('class name', 'submit')
first_name_error_locator = ('id', 'firstname-error')
last_name_error_locator = ('id', 'lastname-error')
email_error_locator = ('id', 'email_address-error')
password_error_locator = ('id', 'password-error')
confirm_password_error_locator = ('id', 'password-confirmation-error')
account_header_title_locator = ('xpath', '//*[@data-ui-id="page-title-wrapper"]')
congrats_notice_locator = ('xpath', '//*[@data-ui-id="message-success"]/div')
