products_list_locator = ('class name', 'product-item-info')
add_to_compare_button_locator = ('xpath', '//*[@title="Add to Compare"]')
compare_section_locator = ('class name', 'odd')
add_to_cart_button_locator = ('xpath', '(//*[@title="Add to Cart"])[1]')
notification_alert_locator = ('xpath', '//*[@data-ui-id="message-notice"]/div')
product_size_locator = ('xpath', '(//*[@id="option-label-size-143-item-171"])[1]')
product_color_locator = ('xpath', '(//*[@id="option-label-color-93-item-49"])[1]')
counter_number_locator = ('class name', 'counter-number')
