iframe = ('tag name', 'iframe')
adv_locator = ('id', 'google_image_div')
shop_deals_button_locator = ('xpath', '//*[@class="more button"]')
minicart_logo_locator = ('class name', 'showcart')
minicart_content_locator = ('class name', 'subtitle')
